[main]
font=JetBrainsMono Nerd Font:size=11, monospace:size=11

[colors-dark]
# No transparency
alpha=1.0

# Base colors
foreground=d8dee9   # Nord4: Snow Storm
background=2e3440   # Nord0: Polar Night

# Normal colors
regular0=3b4252     # Nord1
regular1=bf616a     # Nord11
regular2=a3be8c     # Nord14
regular3=ebcb8b     # Nord13
regular4=81a1c1     # Nord9
regular5=b48ead     # Nord15
regular6=88c0d0     # Nord8
regular7=e5e9f0     # Nord5

# Bright colors
bright0=4c566a      # Nord3
bright1=bf616a      # Nord11
bright2=a3be8c      # Nord14
bright3=ebcb8b      # Nord13
bright4=81a1c1      # Nord9
bright5=b48ead      # Nord15
bright6=8fbcbb      # Nord7
bright7=eceff4      # Nord6
